In [88]:
from pandas import*
from numpy import*
from datetime import*
import time as t
print(data['In-app Purchases'].isnull().sum())
data=read_csv('appstore_games (5).csv')
data=data.drop(['URL','ID','Description','Icon URL','Subtitle','Developer','Primary Genre'],axis=1)
data=data.dropna(subset=['User Rating Count'])
data=data.dropna()
data.head(10)
data['Genres'].unique()
data.head()

0

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Languages,Size,Genres,Original Release Date,Current Version Release Date
5,Sudoku - Classic number puzzle,3.0,47.0,0.0,1.99,4+,EN,48672768.0,"Games, Entertainment, Strategy, Puzzle",30/07/2008,29/04/2019
15,Awele/Oware - Mancala HD,3.0,112.0,0.0,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,"Games, Strategy, Board",31/08/2008,6/04/2015
16,Awele/Oware - Mancala HD,3.0,112.0,0.0,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,"Games, Strategy, Board",31/08/2008,6/04/2015
18,Catcha Mouse,3.5,95971.0,0.0,"1.99, 0.99, 1.99, 0.99, 4.99, 1.99, 1.99",4+,EN,26820692.0,"Games, Puzzle, Strategy",19/02/2009,26/04/2013
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.0,"0.99, 0.99, 0.99",4+,EN,52236288.0,"Games, Strategy, Puzzle, Entertainment",24/09/2008,26/04/2019

In [89]:
data1=data['Genres'].str.split(",",expand=True)
data1.columns =['q','w','e','r']
for i in ['q','w','e','r']:
    data2=data1[i].str.replace("Games","")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Entertainment","")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Utilities","")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Strategy","")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Role Playing","Role_Playing")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Social Networking","Social_Networking")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Health & Fitness","Health_&_Fitness")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Food & Drink","Food_&_Drink")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Racing","Adventure")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
for i in ['w','e','r','q']:
    data2=data1[i].str.replace("Finance","Family")
    data1=data1.drop([i],axis=1)
    data1[i]=data2
    
data1.head(10)

          w            e            r q
5                              Puzzle
15                 Board         None
16                 Board         None
18   Puzzle                      None
19                Puzzle
26                Action
31     Card                      None
38                         Simulation
54            Simulation
59                Action

In [90]:
data1['r'].fillna(value='', inplace=True)
data1['Genres']=data1.w+data1.e+data1.r+data1.q
data1['Genres'].unique()

array(['   Puzzle', '  Board', ' Puzzle ', '  Puzzle ', '  Action ',
       ' Card ', '   Simulation', '  Simulation ', ' Board ',
       '  Adventure ', '   Role_Playing', ' Family  ', '  Family ',
       '  Simulation', '  Puzzle', ' Puzzle  ', ' Board  ', '  Board ',
       ' Action  ', ' Puzzle  Education', ' Role_Playing ', '  Card ',
       ' Simulation  Family', ' Travel  Word', ' Adventure ',
       ' Simulation  ', '   Action', ' Board Business ',
       ' Family Travel ', ' Action ', ' Lifestyle Simulation ',
       '   Casual', ' Social_Networking Simulation ', ' Board Lifestyle ',
       ' Adventure  Medical', '  Sports Sports', ' Card  ',
       ' Board Education ', ' Role_Playing  ', ' Casino  ', '  ',
       '  Role_Playing ', '  Role_Playing', '  Puzzle Education',
       '   Board', ' Casual ', '  Casual', '  Card', '  Action',
       ' Education Puzzle ', ' Simulation ', ' Trivia  Lifestyle',
       '  Adventure', '   Adventure', '   Card', '  Casual Sports',
       '  Casual ', '  Board Lifestyle', '  Board Books', ' Casual  ',
       ' Education Board ', '  Family Social_Networking', nan,
       '  Simulation Education', '  Trivia ', ' Board  Education',
       ' Role_Playing  Reference', '  Simulation Family',
       '   SimulationTravel', '  Education Puzzle', '  Education Board',
       '  Board Social_Networking', ' Sports Sports ',
       ' Action  Business', ' Family  Lifestyle', ' Adventure  ',
       '  Music Action', '   Family', ' Family ', ' Adventure  Lifestyle',
       ' Simulation  Productivity', ' Books Board ', '  Sports ',
       '   Sports', '  Reference Trivia', ' Sports  Sports',
       '  Reference Role_Playing', '  Word ', '  Music Music',
       '  Lifestyle Role_Playing', ' Education  Puzzle',
       ' Role_Playing  Education', ' Education Simulation ', '  Family',
       ' Puzzle Education ', '  Trivia Education', ' Board Reference ',
       ' Food_&_Drink Simulation ', '  Sports',
       ' Navigation  Role_Playing', ' Word  ', ' Health_&_Fitness ',
       ' Role_Playing Reference ', ' Role_Playing  Lifestyle',
       '  Sports Adventure', ' Role_Playing Social_Networking ',
       '  Family Education', ' Action Social_Networking ',
       ' Education  Board', ' Sports Simulation ', '   Music',
       ' Music Action ', ' Education Role_Playing ',
       ' Social_Networking Role_Playing ', ' Music ',
       ' Adventure Sports ', ' Sports Casino ', ' Education ',
       ' Navigation Board ', ' Simulation  Social_Networking',
       ' Education Trivia ', '  Reference', '  Adventure Lifestyle',
       '   TriviaEducation', ' Social_Networking  Role_Playing',
       '  Board Education', '   PuzzleEducation', '  Education Word',
       ' Trivia ', ' Music  ', ' Sports  ', '  Social_Networking',
       ' Adventure  Social_Networking', ' Education  Word',
       ' Role_Playing Food_&_Drink ', ' Role_Playing  Books',
       ' Music Adventure ', ' Social_Networking Board ', '   ActionNews',
       '  Music ', ' Books Adventure ', ' Puzzle Lifestyle ',
       '  Action Food_&_Drink', ' Board  Reference',
       '  Role_Playing Social_Networking', '   Trivia', '   SportsSports',
       '  Music', ' Casual  Lifestyle', '  Education Card',
       ' Board  Music', '  Puzzle Health_&_Fitness',
       ' Family Productivity ', ' Simulation Travel ', ' Word ',
       ' Simulation  Sports', ' Social_Networking  Casual',
       ' Card  Travel', '  Food_&_Drink Casual', ' Sports ',
       ' Family Sports ', ' Education Word ', ' Food_&_Drink Puzzle ',
       '  Business', '  Trivia', '  Lifestyle Casual',
       ' Sports  Simulation', '  Casual Lifestyle',
       ' Food_&_Drink  Role_Playing', ' Word  Social_Networking',
       '  Role_Playing Productivity', ' Family Simulation ',
       '  Medical Role_Playing', ' Lifestyle  Puzzle', ' Puzzle  Travel',
       ' Board  Sports', ' Sports  Board',
       ' Health_&_Fitness  Role_Playing', ' Reference Board ',
       ' Casual Sports ', '  Puzzle Family', ' Puzzle  Lifestyle',
       ' Casual  Music', '  Role_Playing Books', ' Education Adventure ',
       ' Sports  Card', ' Sports  Lifestyle', ' Puzzle Food_&_Drink ',
       '   Word', '  Action Sports', ' Travel Puzzle ', ' Puzzle Family ',
       ' Card  Education', ' Simulation  Education',
       ' Simulation Food_&_Drink ', ' Role_Playing  Social_Networking',
       ' Education  Adventure', ' News Casual ', ' Casual Reference ',
       '  Lifestyle Action', ' Travel Action ', '   SimulationReference',
       '  Card Education', '  Family Role_Playing', ' Education  Trivia',
       ' Card  Health_&_Fitness', '   FamilyHealth_&_Fitness',
       '  Music Simulation', '  Education', '  Puzzle Food_&_Drink',
       ' Education  Role_Playing', '  Puzzle Travel', '   Casino',
       '  Role_Playing Music', '  Social_Networking Board',
       ' Travel  Puzzle', ' Simulation Lifestyle ',
       ' Simulation Productivity ', '  Board Sports', ' Puzzle Travel ',
       ' Action Sports ', '  Lifestyle Board', '  Sports Simulation',
       '  Word', ' Lifestyle Role_Playing ', ' Health_&_Fitness Puzzle ',
       ' Adventure  Reference', '  News Role_Playing',
       ' Social_Networking  Puzzle', ' Simulation Education ',
       '  Travel Puzzle', '   Role_PlayingHealth_&_Fitness',
       '   ActionReference', '  Action Books', ' Photo & Video ',
       '  Role_Playing Education', '  Social_Networking Action',
       ' Trivia  ', '  Role_Playing Health_&_Fitness',
       ' Education  Simulation', ' Family  Puzzle',
       ' Simulation  Business', '  News Puzzle',
       ' Social_Networking  Board', ' Board  Social_Networking',
       '  Social_Networking Role_Playing', ' Action  Lifestyle',
       '   SimulationProductivity', ' Adventure Lifestyle ',
       ' Puzzle  Photo & Video', ' Social_Networking  Action',
       ' Food_&_Drink  Puzzle', '  Word Social_Networking',
       ' Word Social_Networking ', ' Business Board ',
       '  Photo & Video Sports', ' Casino ', '   SimulationFamily',
       ' Card Social_Networking ', ' Adventure  Productivity',
       '  Travel Simulation', '  Role_Playing Reference', ' Music Word ',
       '  Sports Role_Playing', ' Social_Networking Puzzle ',
       ' Education  Casual', '  Action Productivity', '  Casino ',
       '  Education Family', ' Lifestyle Puzzle ', ' Simulation  Music',
       ' Role_Playing Health_&_Fitness ', '  Sports Card',
       ' Family  Simulation', '   WordBooks', ' Board  Lifestyle',
       ' Sports  Adventure', ' Adventure  Photo & Video',
       ' Simulation Business ', ' Social_Networking  Card',
       '  Action Reference', ' Action  Sports', ' Action Music ',
       ' Simulation  Food_&_Drink', ' Lifestyle  Role_Playing',
       '  Education Simulation', ' Board  Productivity',
       ' Education Card ', '  Puzzle Lifestyle', ' Casual  Education',
       ' Lifestyle Family ', '  Casual Education', '  Family Puzzle',
       ' Simulation Family ', '  Casual Food_&_Drink', ' Word Books ',
       '  Role_Playing Lifestyle', '  Card Social_Networking',
       ' Business Simulation ', ' Sports Card ', ' Education Casual ',
       '  Trivia Lifestyle', '  Food_&_Drink Role_Playing',
       ' Travel  Adventure', '  Adventure Productivity',
       ' Role_Playing Lifestyle ', ' Lifestyle Casual ',
       '  Social_Networking Adventure', ' Social_Networking  Adventure',
       '  Lifestyle Music', '  Music Adventure',
       '  Social_Networking Card', '  Education Casual',
       ' Magazines & Newspapers Board ', ' Simulation  Lifestyle',
       ' Role_Playing  Food_&_Drink', ' Simulation Sports ',
       '  Family Food_&_Drink', '  Simulation Business'], dtype=object)

In [91]:
data1['Genres'].str.split(",",n=1,expand=True)
data1.head(10)

          w            e            r q         Genres
5                              Puzzle           Puzzle
15                 Board                         Board
16                 Board                         Board
18   Puzzle                                    Puzzle
19                Puzzle                       Puzzle
26                Action                       Action
31     Card                                      Card
38                         Simulation       Simulation
54            Simulation                   Simulation
59                Action                       Action

In [92]:
d1=data['Original Release Date'].str.split('/',expand=True)
d2=data['Current Version Release Date'].str.split('/',expand=True)
d1['Date']=to_datetime(data['Original Release Date'])
d2['Date']=to_datetime(data['Current Version Release Date'])
d2['diff']=(d2['Date']-d1['Date'])
d2['diff']=d2['diff']/np.timedelta64(1,'M')
d2=d2.drop(['Date',0,1,2],axis=1)
data['last update']=d2
data.head()

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Languages,Size,Genres,Original Release Date,Current Version Release Date,last update
5,Sudoku - Classic number puzzle,3.0,47.0,0.0,1.99,4+,EN,48672768.0,"Games, Entertainment, Strategy, Puzzle",30/07/2008,29/04/2019,128.955420
15,Awele/Oware - Mancala HD,3.0,112.0,0.0,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,"Games, Strategy, Board",31/08/2008,6/04/2015,81.085854
16,Awele/Oware - Mancala HD,3.0,112.0,0.0,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,"Games, Strategy, Board",31/08/2008,6/04/2015,81.085854
18,Catcha Mouse,3.5,95971.0,0.0,"1.99, 0.99, 1.99, 0.99, 4.99, 1.99, 1.99",4+,EN,26820692.0,"Games, Puzzle, Strategy",19/02/2009,26/04/2013,50.169408
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.0,"0.99, 0.99, 0.99",4+,EN,52236288.0,"Games, Strategy, Puzzle, Entertainment",24/09/2008,26/04/2019,127.016982

In [93]:
dat=data1['Genres'].str.split(' ',expand=False)
for i in dat.keys():
    if 'float' in str(type(dat[i])):
        continue
    for j in dat[i]:
        if j == '' or j == ' ':
            dat[i].remove(j)
    for j in dat[i]:
        if j == '' or j == ' ':
            dat[i].remove(j)    
dat.tail(50)

16475                   [Puzzle]
16478                        NaN
16479               [Simulation]
16480               [Simulation]
16485                        NaN
16487                    [Board]
16501                   [Action]
16508               [Simulation]
16514               [Simulation]
16515               [Simulation]
16519                   [Puzzle]
16524       [Sports, Simulation]
16525               [Simulation]
16528     [Simulation, Business]
16529                    [Board]
16536               [Simulation]
16543                   [Trivia]
16548               [Simulation]
16552                   [Puzzle]
16553                   [Casual]
16569               [Simulation]
16580               [Simulation]
16588               [Simulation]
16596                   [Puzzle]
16601           [Sports, Sports]
16606               [Simulation]
16629                        NaN
16634             [Role_Playing]
16647               [Simulation]
16651    [Simulation, Education]
16654             [Role_Playing]
16694                   [Puzzle]
16708                   [Action]
16716             [Role_Playing]
16718                   [Puzzle]
16729               [Simulation]
16735               [Simulation]
16740        [Puzzle, Education]
16748                   [Casino]
16758                     [Card]
16763                   [Casual]
16772             [Role_Playing]
16781                [Adventure]
16789               [Simulation]
16791                   [Casual]
16828                   [Puzzle]
16842                   [Action]
16856               [Simulation]
16863                    [Board]
16932                    [Board]
Name: Genres, dtype: object

In [94]:
for i in dat.keys():
    if 'float' in str(type(dat[i])):
        continue
    for j in dat[i]:
        if j== 'Board':
            dat[i].remove(j)
            dat[i].append('Puzzle')
        if j== 'Playing':
            dat[i].remove(j)
            dat[i].append('Puzzle')
        if j== 'Role':
            dat[i].remove(j)
            dat[i].append('Adventure')
        if j== 'Role_Playing':
            dat[i].remove(j)
            dat[i].append('Adventure')
        if j== 'Education':
            dat[i].remove(j)
            dat[i].append('Family')
        if j== 'Card':
            dat[i].remove(j)
            dat[i].append('Family')
        if j== 'Photo_&_Video':
            dat[i].remove(j)
            dat[i].append('Family')
        if j== 'Food_&_Drink':
            dat[i].remove(j)
            dat[i].append('Family')
dat

5            [Puzzle]
15           [Puzzle]
16           [Puzzle]
18           [Puzzle]
19           [Puzzle]
             ...
16828        [Puzzle]
16842        [Action]
16856    [Simulation]
16863        [Puzzle]
16932        [Puzzle]
Name: Genres, Length: 4618, dtype: object

In [95]:
for i in dat.keys():
    if 'float' in str(type(dat[i])):
        continue
    dat[i]=','.join(dat[i])
dat.head(10)

5         Puzzle
15        Puzzle
16        Puzzle
18        Puzzle
19        Puzzle
26        Action
31        Family
38    Simulation
54    Simulation
59        Action
Name: Genres, dtype: object

In [96]:
Data=data.drop(['Genres'],axis=1)
Data['Genres']=dat
Data.head(10)

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Languages,Size,Original Release Date,Current Version Release Date,last update,Genres
5,Sudoku - Classic number puzzle,3.0,47.0,0.00,1.99,4+,EN,48672768.0,30/07/2008,29/04/2019,128.955420,Puzzle
15,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
16,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
18,Catcha Mouse,3.5,95971.0,0.00,"1.99, 0.99, 1.99, 0.99, 4.99, 1.99, 1.99",4+,EN,26820692.0,19/02/2009,26/04/2013,50.169408,Puzzle
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.00,"0.99, 0.99, 0.99",4+,EN,52236288.0,24/09/2008,26/04/2019,127.016982,Puzzle
26,Fieldrunners,4.0,41869.0,2.99,"0.99, 0.99, 0.99, 0.99",9+,EN,75041792.0,5/10/2008,11/04/2018,125.834206,Action
31,Edgewise,3.5,23.0,0.00,"1.99, 0.99",4+,EN,1298432.0,25/10/2008,26/06/2015,80.001643,Family
38,TapDefense,3.5,273687.0,0.00,"0.99, 2.99, 1.99",9+,EN,7774384.0,24/11/2008,5/12/2012,41.561428,Simulation
54,Antivirus,3.0,187.0,0.00,1.99,9+,EN,25563136.0,3/02/2009,9/07/2015,78.194624,Simulation
59,Wedding Dash Deluxe,4.5,17056.0,0.99,"0.0, 0.99, 5.99, 0.99, 0.99, 0.99, 0.99, 0.99,...",4+,EN,55803904.0,28/01/2009,2/07/2014,60.321567,Action

In [97]:
Data1= Data[(Data['User Rating Count']<=200) & (Data['last update']<=6)]
idx=Data1.index
for i in idx:
    Data =Data.drop([i],axis=0)
Data=Data.dropna(subset=['Genres'])
Data.head(10)

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Languages,Size,Original Release Date,Current Version Release Date,last update,Genres
5,Sudoku - Classic number puzzle,3.0,47.0,0.00,1.99,4+,EN,48672768.0,30/07/2008,29/04/2019,128.955420,Puzzle
15,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
16,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
18,Catcha Mouse,3.5,95971.0,0.00,"1.99, 0.99, 1.99, 0.99, 4.99, 1.99, 1.99",4+,EN,26820692.0,19/02/2009,26/04/2013,50.169408,Puzzle
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.00,"0.99, 0.99, 0.99",4+,EN,52236288.0,24/09/2008,26/04/2019,127.016982,Puzzle
26,Fieldrunners,4.0,41869.0,2.99,"0.99, 0.99, 0.99, 0.99",9+,EN,75041792.0,5/10/2008,11/04/2018,125.834206,Action
31,Edgewise,3.5,23.0,0.00,"1.99, 0.99",4+,EN,1298432.0,25/10/2008,26/06/2015,80.001643,Family
38,TapDefense,3.5,273687.0,0.00,"0.99, 2.99, 1.99",9+,EN,7774384.0,24/11/2008,5/12/2012,41.561428,Simulation
54,Antivirus,3.0,187.0,0.00,1.99,9+,EN,25563136.0,3/02/2009,9/07/2015,78.194624,Simulation
59,Wedding Dash Deluxe,4.5,17056.0,0.99,"0.0, 0.99, 5.99, 0.99, 0.99, 0.99, 0.99, 0.99,...",4+,EN,55803904.0,28/01/2009,2/07/2014,60.321567,Action

In [98]:
Data.head(10)

,Name,Average User Rating,User Rating Count,Price,In-app Purchases,Age Rating,Languages,Size,Original Release Date,Current Version Release Date,last update,Genres
5,Sudoku - Classic number puzzle,3.0,47.0,0.00,1.99,4+,EN,48672768.0,30/07/2008,29/04/2019,128.955420,Puzzle
15,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
16,Awele/Oware - Mancala HD,3.0,112.0,0.00,0.99,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle
18,Catcha Mouse,3.5,95971.0,0.00,"1.99, 0.99, 1.99, 0.99, 4.99, 1.99, 1.99",4+,EN,26820692.0,19/02/2009,26/04/2013,50.169408,Puzzle
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.00,"0.99, 0.99, 0.99",4+,EN,52236288.0,24/09/2008,26/04/2019,127.016982,Puzzle
26,Fieldrunners,4.0,41869.0,2.99,"0.99, 0.99, 0.99, 0.99",9+,EN,75041792.0,5/10/2008,11/04/2018,125.834206,Action
31,Edgewise,3.5,23.0,0.00,"1.99, 0.99",4+,EN,1298432.0,25/10/2008,26/06/2015,80.001643,Family
38,TapDefense,3.5,273687.0,0.00,"0.99, 2.99, 1.99",9+,EN,7774384.0,24/11/2008,5/12/2012,41.561428,Simulation
54,Antivirus,3.0,187.0,0.00,1.99,9+,EN,25563136.0,3/02/2009,9/07/2015,78.194624,Simulation
59,Wedding Dash Deluxe,4.5,17056.0,0.99,"0.0, 0.99, 5.99, 0.99, 0.99, 0.99, 0.99, 0.99,...",4+,EN,55803904.0,28/01/2009,2/07/2014,60.321567,Action

In [99]:
money=Data['In-app Purchases'].str.split(',',expand=False)
money.isnull().sum()

0

In [100]:
for i in money.keys():
    sum=0
    for j in money[i]:
        j=float(j)
        sum=sum+j
    money[i]=sum
print(money)
Data=Data.drop(['In-app Purchases'],axis=1)
Data['In-app Purchases']=money
Data

5          1.99
15         0.99
16         0.99
18        14.93
19         2.97
          ...
16596     74.92
16647      80.9
16694      50.9
16718      2.99
16729    215.91
Name: In-app Purchases, Length: 3210, dtype: object

,Name,Average User Rating,User Rating Count,Price,Age Rating,Languages,Size,Original Release Date,Current Version Release Date,last update,Genres,In-app Purchases
5,Sudoku - Classic number puzzle,3.0,47.0,0.0,4+,EN,48672768.0,30/07/2008,29/04/2019,128.955420,Puzzle,1.99
15,Awele/Oware - Mancala HD,3.0,112.0,0.0,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle,0.99
16,Awele/Oware - Mancala HD,3.0,112.0,0.0,4+,"EN, FR, DE, IT, ES",122826752.0,31/08/2008,6/04/2015,81.085854,Puzzle,0.99
18,Catcha Mouse,3.5,95971.0,0.0,4+,EN,26820692.0,19/02/2009,26/04/2013,50.169408,Puzzle,14.93
19,"Cool Sudoku, Jigsaw, Killer",3.5,357.0,0.0,4+,EN,52236288.0,24/09/2008,26/04/2019,127.016982,Puzzle,2.97
...,...,...,...,...,...,...,...,...,...,...,...,...
16596,Jewel Adventure - Match 3 Game,4.5,475.0,0.0,4+,"EN, JA, ZH, ZH",109021184.0,16/05/2019,27/06/2019,1.379905,Puzzle,74.92
16647,Super Chef World,4.5,256.0,0.0,4+,EN,652736512.0,26/05/2019,22/06/2019,0.887082,Simulation,80.9
16694,Smash Brickz Pro,4.5,354.0,0.0,4+,EN,211398656.0,11/06/2019,28/07/2019,-3.318343,Puzzle,50.9
16718,Car Wash Empire,5.0,658.0,0.0,4+,EN,206372864.0,5/06/2019,30/07/2019,2.792665,Puzzle,2.99
16729,OG West,5.0,267.0,0.0,12+,"AR, NL, EN, FR, DE, ID, IT, JA, KO, PT, RU, ZH...",282842112.0,18/06/2019,3/08/2019,-3.351198,Simulation,215.91

In [101]:
Data.sort_values('Average User Rating',ascending=False).head(10)

,Name,Average User Rating,User Rating Count,Price,Age Rating,Languages,Size,Original Release Date,Current Version Release Date,last update,Genres,In-app Purchases
5506,RGB - Color Reflex Game,5.0,6.0,0.00,4+,EN,4365312.0,18/02/2015,17/01/2017,22.965564,Casual,0.99
5868,Super Gem Quest 2 - The Jewels (pro version),5.0,67.0,2.99,4+,EN,102100992.0,16/04/2015,21/10/2015,6.176718,Puzzle,57.91
5995,Rabbit Evolution Merge in Farm,5.0,29369.0,0.00,9+,"AR, CA, CS, DA, NL, EN, FI, FR, DE, EL, HE, HU...",57577472.0,26/06/2015,12/03/2019,53.257767,Family,95.92
6073,Tactical War: Tower Defense,5.0,32.0,0.00,12+,EN,304284672.0,4/07/2015,16/02/2019,46.358241,Action,12.95
6089,"Egg, Inc.",5.0,174591.0,0.00,4+,EN,74891264.0,14/07/2016,25/07/2019,36.337502,Simulation,52.93
6167,Giraffe Evolution | Clicker Game of the Mutant...,5.0,4259.0,0.00,9+,EN,73874432.0,15/06/2015,5/09/2016,10.809257,Family,42.9
6177,"""Extreme Job Hero's Manager""",5.0,1951.0,0.00,12+,"EN, JA, KO",192003072.0,19/06/2015,27/05/2019,47.245323,Adventure,247.92
6209,Epic Party Clicker,5.0,3340.0,0.00,9+,EN,82584576.0,20/07/2015,28/05/2019,46.259677,Music,109.91
6277,Bubble Tap - Bubble Popper,5.0,8.0,0.00,4+,EN,7871488.0,25/06/2015,6/09/2016,11.499209,Puzzle,6.96
6343,RaisingStacks,5.0,12.0,0.00,4+,EN,53182464.0,1/12/2015,23/08/2017,31.343559,Casual,0.99

In [102]:
main=Data[Data['Average User Rating']>4.5]
#main.groupby('Genres').describe()
Data['Average User Rating'].unique()
main.groupby('Genres').describe()

                              Average User Rating                           \
                                            count mean  std  min  25%  50%
Genres
Action                                       48.0  5.0  0.0  5.0  5.0  5.0
Adventure                                    47.0  5.0  0.0  5.0  5.0  5.0
Casual                                       22.0  5.0  0.0  5.0  5.0  5.0
Casual,Family                                 1.0  5.0  NaN  5.0  5.0  5.0
Education,Puzzle                              1.0  5.0  NaN  5.0  5.0  5.0
Family                                       34.0  5.0  0.0  5.0  5.0  5.0
Family,Family                                 1.0  5.0  NaN  5.0  5.0  5.0
Family,Simulation                             1.0  5.0  NaN  5.0  5.0  5.0
Lifestyle,Adventure                           2.0  5.0  0.0  5.0  5.0  5.0
Lifestyle,Puzzle                              1.0  5.0  NaN  5.0  5.0  5.0
Lifestyle,Simulation                          1.0  5.0  NaN  5.0  5.0  5.0
Magazines,&,Newspapers,Puzzle                 1.0  5.0  NaN  5.0  5.0  5.0
Music                                         1.0  5.0  NaN  5.0  5.0  5.0
Puzzle                                      107.0  5.0  0.0  5.0  5.0  5.0
Puzzle,Family                                 6.0  5.0  0.0  5.0  5.0  5.0
Simulation                                   51.0  5.0  0.0  5.0  5.0  5.0
Simulation,Music                              1.0  5.0  NaN  5.0  5.0  5.0
SimulationProductivity                        1.0  5.0  NaN  5.0  5.0  5.0
Social_Networking,Adventure                   2.0  5.0  0.0  5.0  5.0  5.0
Social_Networking,Puzzle                      2.0  5.0  0.0  5.0  5.0  5.0
Sports                                        4.0  5.0  0.0  5.0  5.0  5.0
Sports,Sports                                 5.0  5.0  0.0  5.0  5.0  5.0
Travel,Adventure                              1.0  5.0  NaN  5.0  5.0  5.0
Trivia                                        1.0  5.0  NaN  5.0  5.0  5.0

                                        User Rating Count                 ...  \
                               75%  max             count           mean  ...
Genres                                                                    ...
Action                         5.0  5.0              48.0   12525.958333  ...
Adventure                      5.0  5.0              47.0   10320.553191  ...
Casual                         5.0  5.0              22.0     877.090909  ...
Casual,Family                  5.0  5.0               1.0       6.000000  ...
Education,Puzzle               5.0  5.0               1.0     154.000000  ...
Family                         5.0  5.0              34.0    8578.970588  ...
Family,Family                  5.0  5.0               1.0       6.000000  ...
Family,Simulation              5.0  5.0               1.0  146729.000000  ...
Lifestyle,Adventure            5.0  5.0               2.0    1296.500000  ...
Lifestyle,Puzzle               5.0  5.0               1.0       7.000000  ...
Lifestyle,Simulation           5.0  5.0               1.0   11721.000000  ...
Magazines,&,Newspapers,Puzzle  5.0  5.0               1.0     233.000000  ...
Music                          5.0  5.0               1.0    3340.000000  ...
Puzzle                         5.0  5.0             107.0    1707.261682  ...
Puzzle,Family                  5.0  5.0               6.0     182.666667  ...
Simulation                     5.0  5.0              51.0   24027.705882  ...
Simulation,Music               5.0  5.0               1.0   65932.000000  ...
SimulationProductivity         5.0  5.0               1.0       5.000000  ...
Social_Networking,Adventure    5.0  5.0               2.0     840.000000  ...
Social_Networking,Puzzle       5.0  5.0               2.0   45164.500000  ...
Sports                         5.0  5.0               4.0      24.750000  ...
Sports,Sports                  5.0  5.0               5.0      31.200000  ...
Travel,Adventure               5.0  5.0               1.0      11.000000  ...
Trivia                         5.0  5.0               1.0      22.000000  ...

                                      Size               last update  \
                                       75%           max       count
Genres
Action                         417688064.0  2.212521e+09        48.0
Adventure                      239242240.0  2.064627e+09        47.0
Casual                         163400448.0  2.370253e+08        22.0
Casual,Family                   78527488.0  7.852749e+07         1.0
Education,Puzzle               154234880.0  1.542349e+08         1.0
Family                          82775552.0  2.483825e+08        34.0
Family,Family                   56954880.0  5.695488e+07         1.0
Family,Simulation              296638464.0  2.966385e+08         1.0
Lifestyle,Adventure            700060160.0  7.833825e+08         2.0
Lifestyle,Puzzle                15773696.0  1.577370e+07         1.0
Lifestyle,Simulation           201666560.0  2.016666e+08         1.0
Magazines,&,Newspapers,Puzzle   41719808.0  4.171981e+07         1.0
Music                           82584576.0  8.258458e+07         1.0
Puzzle                         116679680.0  4.795505e+08       107.0
Puzzle,Family                   96731392.0  1.391688e+08         6.0
Simulation                     251277824.0  4.452188e+08        51.0
Simulation,Music               248890368.0  2.488904e+08         1.0
SimulationProductivity          95902720.0  9.590272e+07         1.0
Social_Networking,Adventure    288236544.0  3.690988e+08         2.0
Social_Networking,Puzzle       118744320.0  1.439263e+08         2.0
Sports                         372542208.0  4.150733e+08         4.0
Sports,Sports                  193467392.0  2.597417e+08         5.0
Travel,Adventure               135547904.0  1.355479e+08         1.0
Trivia                          80629760.0  8.062976e+07         1.0

                                                                           \
                                    mean        std        min        25%
Genres
Action                         29.295605  24.520591   0.000000   9.725046
Adventure                      24.145544  22.690033  -1.182776   9.527916
Casual                         18.495806  11.595877   3.745457   8.484774
Casual,Family                   8.049447        NaN   8.049447   8.049447
Education,Puzzle               27.368118        NaN  27.368118  27.368118
Family                         19.454923  20.751602  -7.983737   3.630465
Family,Family                  10.053595        NaN  10.053595  10.053595
Family,Simulation              19.220107        NaN  19.220107  19.220107
Lifestyle,Adventure             8.016592   4.181744   5.059652   6.538122
Lifestyle,Puzzle               44.058400        NaN  44.058400  44.058400
Lifestyle,Simulation           15.310376        NaN  15.310376  15.310376
Magazines,&,Newspapers,Puzzle   1.708454        NaN   1.708454   1.708454
Music                          46.259677        NaN  46.259677  46.259677
Puzzle                         28.200852  22.222816  -4.599684  11.532064
Puzzle,Family                  22.998419  18.912066   6.143863  10.423212
Simulation                     18.052148  18.110197  -3.351198   6.028871
Simulation,Music               23.951210        NaN  23.951210  23.951210
SimulationProductivity         16.920265        NaN  16.920265  16.920265
Social_Networking,Adventure    19.137970  27.065177   0.000000   9.568985
Social_Networking,Puzzle       33.774821  22.488490  17.873057  25.823939
Sports                         12.821619   9.363253   7.063800   7.655188
Sports,Sports                  36.672622  19.937344  16.164603  25.363971
Travel,Adventure                7.228074        NaN   7.228074   7.228074
Trivia                         33.084868        NaN  33.084868  33.084868


                                     50%        75%         max
Genres
Action                         20.468593  43.721637   90.909464
Adventure                      15.277521  30.374340  101.390172
Casual                         16.903838  23.885501   41.331444
Casual,Family                   8.049447   8.049447    8.049447
Education,Puzzle               27.368118  27.368118   27.368118
Family                         11.466355  30.316844   68.732418
Family,Family                  10.053595  10.053595   10.053595
Family,Simulation              19.220107  19.220107   19.220107
Lifestyle,Adventure             8.016592   9.495062   10.973531
Lifestyle,Puzzle               44.058400  44.058400   44.058400
Lifestyle,Simulation           15.310376  15.310376   15.310376
Magazines,&,Newspapers,Puzzle   1.708454   1.708454    1.708454
Music                          46.259677  46.259677   46.259677
Puzzle                         22.439886  38.407359  104.248547
Puzzle,Family                  19.729358  25.142200   58.120290
Simulation                     11.137806  27.630958   74.186328
Simulation,Music               23.951210  23.951210   23.951210
SimulationProductivity         16.920265  16.920265   16.920265
Social_Networking,Adventure    19.137970  28.706955   38.275940
Social_Networking,Puzzle       33.774821  41.725703   49.676585
Sports                          8.722972  13.889402   26.776731
Sports,Sports                  31.540689  42.251381   68.042465
Travel,Adventure                7.228074   7.228074    7.228074
Trivia                         33.084868  33.084868   33.084868

[24 rows x 40 columns]

In [103]:
#Here we can see that 'Puzzle' Genre is more favourable to have higher rating

In [104]:
main.groupby('Age Rating').describe()
#by this table we can say that the games having age rating of 4+ is more favourable to have higher rating

           Average User Rating                                     \
                         count mean  std  min  25%  50%  75%  max
Age Rating
12+                       57.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
17+                        9.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
4+                       194.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
9+                        82.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0

           User Rating Count                ...         Size                \
                       count          mean  ...          75%           max
Age Rating                                  ...
12+                     57.0  14535.894737  ...  304284672.0  2.212521e+09
17+                      9.0  31445.111111  ...  248890368.0  3.182879e+08
4+                     194.0   6495.752577  ...  138855424.0  5.130537e+08
9+                      82.0   9241.146341  ...  236345856.0  1.389541e+09

           last update                                                        \
                 count       mean        std       min        25%        50%
Age Rating
12+               57.0  24.622142  21.638946 -3.351198   9.429352  18.792994
17+                9.0  17.146599   6.943786  8.246576  12.813405  16.066038
4+               194.0  24.884696  20.910940 -7.983737   8.509415  19.187252
9+                82.0  23.290907  22.721278 -3.055504   7.827676  14.718988


                  75%         max
Age Rating
12+         31.934947   90.909464
17+         22.505596   26.776731
4+          36.805684  104.248547
9+          31.179285  101.390172

[4 rows x 40 columns]

In [109]:
main.groupby('Price').describe()
#Here we can easily conclude that the games having zero price have higher user rating

      Average User Rating                                     \
                    count mean  std  min  25%  50%  75%  max
Price
0.00                309.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
0.99                  6.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
1.99                  6.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
2.99                 11.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
3.99                  2.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0
4.99                  8.0  5.0  0.0  5.0  5.0  5.0  5.0  5.0

      User Rating Count                ...         Size                \
                  count          mean  ...          75%           max
Price                                  ...
0.00              309.0   9181.466019  ...  206372864.0  2.212521e+09
0.99                6.0   2644.666667  ...   60251904.0  2.942566e+08
1.99                6.0   3021.000000  ...  128876288.0  2.426051e+08
2.99               11.0  13661.090909  ...  195856384.0  4.629586e+08
3.99                2.0     67.000000  ...  162319872.0  2.024673e+08
4.99                8.0  13503.625000  ...  633326592.0  8.004762e+08

      last update                                                         \
            count       mean        std        min        25%        50%
Price
0.00        309.0  22.540364  19.401716  -7.983737   8.246576  16.558862
0.99          6.0  39.655845  27.818058  12.222017  15.679993  37.684552
1.99          6.0  43.379399  42.813848   6.176718   7.507341  30.160784
2.99         11.0  43.419223  32.514507   6.176718  11.794903  55.951868
3.99          2.0  46.719645  17.191614  34.563338  40.641492  46.719645
4.99          8.0  32.629007  22.216042   6.833816  15.811413  29.536541


             75%         max
Price
0.00   31.934947  101.390172
0.99   54.760878   81.545822
1.99   74.720220  104.248547
2.99   74.071336   76.683299
3.99   52.797799   58.875952
4.99   46.120044   68.962402

[6 rows x 32 columns]

In [106]:
main['Size'].mean()
#Here we can see that the most favourable size of the game to have higher rating is 166730686.57894737

166730686.57894737

In [107]:
main['In-app Purchases'].mean()
#Here we can say that for a game to have higher user rating on average it should have In-app Purchases of 59.93

56.930058479532114

In [108]:
#for combinations the games from 'puzzle' Genre and age of 4+ are most likely to have higher user rating